### ISSUE TITLE
Implementing OAuth server

### ISSUE THREAD

**Issue by clifinger** [canduma/canduma#11]
What do you think about using [oxide-auth](https://github.com/HeroicKatora/oxide-auth) ?
```sh
$ cargo run --example actix
```

**Comment by DOCS-kdu3** [comment]
This crate seems like the most mature open-source server oauth implementation in the rust ecosystem. I think it is a good decision.

**Comment by clifinger** [comment]
@DOCS-kdu3 can you implement it ?

**Comment by eastuto** [comment]
@clifinger I can have a look at this if you like

**Comment by clifinger** [comment]
@eastuto thank you :)
